PatchRecipeSpec {
    recipe_id: "python_cli_tool_csv_report_new_patch_lane",
    family_id: "python_cli_tool",
    tool_kind: Some("csv_report"),
    patch_kind: "new_patch_lane",
    dependency_mode: "standalone",
    requires_features: &[],
    provides_features: &["todo_feature"],
    request_match_any: &["todo phrase"],
    request_match_all: &[],
    handler: crate::patch_python_cli_tool_csv_report_new_patch_lane,
},
