PatchRecipeSpec {
    recipe_id: "rust_cli_tool_log_summary_new_patch_lane",
    family_id: "rust_cli_tool",
    tool_kind: Some("log_summary"),
    patch_kind: "new_patch_lane",
    dependency_mode: "standalone",
    requires_features: &[],
    provides_features: &["todo_feature"],
    request_match_any: &["todo phrase"],
    request_match_all: &[],
    handler: crate::patch_rust_cli_tool_log_summary_new_patch_lane,
},
