[package]
name = "chatty_factory_families"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = { workspace = true }
chatty_factory_core = { path = "../chatty_factory_core" }
chatty_factory_templates = { path = "../chatty_factory_templates" }
serde_json = { workspace = true }
